;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Maple/Table/Tags/ActionBehaviorTags.ActionBehaviorTags
+GameplayTagTableList=/Game/Maple/Table/Tags/DialogsgsameplayTags.DialogsgsameplayTags
+GameplayTagTableList=/Game/Maple/Table/Tags/EnemyTypeTags.EnemyTypeTags
+GameplayTagTableList=/Game/Maple/Table/Tags/FigshtTags.FigshtTags
+GameplayTagTableList=/Game/Maple/Table/Tags/NPCStateTags.NPCStateTags
+GameplayTagTableList=/Game/Maple/Table/Tags/StateTags.StateTags
+GameplayTagTableList=/Game/Maple/Table/Tags/ConsumablesTags.ConsumablesTags
+GameplayTagRedirects=(OldTagName="Data.EnergyCost",NewTagName="Data.Cost.Energy")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Cost.Energy",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Slow",DevComment="")
+GameplayTagList=(Tag="Test.TestSkills",DevComment="")

